<a href="https://colab.research.google.com/github/Veenabs5/LR/blob/main/LR1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas_profiling import ProfileReport
import pickle

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/justmarkham/scikit-learn-videos/master/data/Advertising.csv")

In [ ]:
df

Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [ ]:
df.describe()

Unnamed: 0          TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [ ]:
df = pd.DataFrame(df)

In [ ]:
ProfileReport(df)

TypeError: ignored

In [ ]:
!pip install pandas-profiling

In [ ]:
from pandas_profiling import ProfileReport

In [ ]:
profile= ProfileReport(df)

TypeError: ignored

In [ ]:
profile = ProfileReport(df)
profile

TypeError: ignored

In [ ]:
profile.to_widgets()

NameError: ignored

In [ ]:
profile.to_file('test.html')

NameError: ignored

In [ ]:
! pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip 

     \ 25.9 MB 710 kB/s
     |████████████████████████████████| 10.9 MB 17.2 MB/s 
     |████████████████████████████████| 596 kB 52.6 MB/s 
     |████████████████████████████████| 102 kB 12.6 MB/s 
     |████████████████████████████████| 690 kB 58.7 MB/s 
     |████████████████████████████████| 4.7 MB 62.6 MB/s 
     |████████████████████████████████| 63 kB 1.7 MB/s 
     |████████████████████████████████| 812 kB 63.1 MB/s 
     |████████████████████████████████| 38.1 MB 1.1 MB/s 
  Created wheel for pandas-profiling: filename=pandas_profiling-3.1.1-py2.py3-none-any.whl size=261287 sha256=739661bb877c59e0215f8e3d000c3b879174bf26a46b2ca279b45fc3fa6c7d9c
  Stored in directory: /tmp/pip-ephem-wheel-cache-8mulncjc/wheels/cc/d5/09/083fb07c9363a2f45854b0e3a7de7d7c560f07da74b9e9769d
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27098 sha256=d61f5130ca9ad4a5613d5f6e20d8901bce7ac5de0456885aa6ccbcb85e813321
  Stored in directory: /root/.cache/pip/wheels/70/e1/52/5b1

In [ ]:
profile = ProfileReport(df,title="Heart Disease", html={'style':{'full_width':True}})

OSError: ignored

In [ ]:

! pip install pandas==0.25

     |████████████████████████████████| 10.4 MB 22.2 MB/s 
  Attempting uninstall: pandas
    Found existing installation: pandas 1.3.5
    Uninstalling pandas-1.3.5:
      Successfully uninstalled pandas-1.3.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xarray 0.18.2 requires pandas>=1.0, but you have pandas 0.25.0 which is incompatible.
visions 0.7.4 requires pandas>=0.25.3, but you have pandas 0.25.0 which is incompatible.
phik 0.12.2 requires pandas>=0.25.1, but you have pandas 0.25.0 which is incompatible.
pandas-profiling 3.1.1 requires pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3, but you have pandas 0.25.0 which is incompatible.
google-colab 1.0.0 requires pandas>=1.1.0; python_version >= "3.0", but you have pandas 0.25.0 which is incompatible.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.27.1 which is incompatible.
fbprop

In [ ]:
profile = ProfileReport(df, title="Pandas Profiling Report")


OSError: ignored

In [ ]:
plt.style.use('file:///usr/share/mygraph/mystyle.mplstyle')

OSError: ignored

In [ ]:
from pandas.core.frame import DataFrame
x=df['TV']
type(x)


pandas.core.series.Series

In [ ]:
x=pd.DataFrame(x)

In [ ]:
y=df.Sales
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64

In [ ]:
from sklearn.linear_model import LinearRegression


In [ ]:
m1=LinearRegression()

In [ ]:
m1.fit(x,y)

LinearRegression()

In [ ]:
m1.intercept_

7.032593549127695

In [ ]:
m1.coef_

array([0.04753664])

In [ ]:
file='linear_reg.sav'
pickle.dump(m1,open(file,'wb'))
import os
os.getcwd()

'/content'

In [ ]:
m1.predict([[45]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([9.17174237])

In [ ]:
l=[6,8,9,90,87]

In [ ]:
for i in l :
  print(m1.predict([[i]]))

[7.31781339]
[7.41288667]
[7.46042331]
[11.31089119]
[11.16828127]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not h

In [ ]:
df

Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [ ]:
data_x=df[['TV','Radio','Newspaper']]
data_x

TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [ ]:
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64

In [ ]:
lm= LinearRegression()
lm.fit(data_x,y)

LinearRegression()

In [ ]:
lm.intercept_

2.938889369459412

In [ ]:
lm.coef_

array([ 0.04576465,  0.18853002, -0.00103749])

In [ ]:
lm.score(data_x,y)

0.8972106381789522

In [ ]:
data_x2=df[["TV","Radio"]]
y


In [ ]:
lm2=LinearRegression()
lm2.fit(data_x,y)
lm2.score(data_x,y)

0.8972106381789522

In [ ]:
#impact analysis for feauture selection

In [ ]:
#statistical modeling approch(above one cyclic model)

In [ ]:
! pip install --upgrade Cython
! pip install --upgrade git+https://github.com/statsmodels/statsmodels
import statsmodels.api as sm

  Cloning https://github.com/statsmodels/statsmodels to /tmp/pip-req-build-zz_v8mi4
  Running command git clone -q https://github.com/statsmodels/statsmodels /tmp/pip-req-build-zz_v8mi4


In [ ]:
lm=smf.ols(formula='sales~TV+Radio+Newspaer',data=df).fit()
lm.summary()